# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.

[package]
license = "AGPL-3.0-or-later"
name = "tool-egress-pull"
version = "1.0.0"
edition = "2021"
authors = ["PointSav Digital Systems"]
description = "Manual Asymmetric Storage Client. Pulls, rebuilds, and wipes."

[dependencies]

[workspace]
