use std::time::Duration;

/// Build a blocking reqwest client with an optional trusted root PEM certificate.
///
/// When `cert_pem` is `Some`, the PEM bytes are added as a trusted root so that
/// self-signed certs (e.g. those generated by service-ingress) are accepted.
/// When `None`, the system CA pool is used.
pub fn build_http_client(
    cert_pem: Option<&[u8]>,
    timeout_secs: u64,
) -> reqwest::blocking::Client {
    let mut builder =
        reqwest::blocking::Client::builder().timeout(Duration::from_secs(timeout_secs));
    if let Some(pem) = cert_pem {
        if let Ok(cert) = reqwest::Certificate::from_pem(pem) {
            builder = builder.add_root_certificate(cert);
        }
    }
    builder.build().unwrap_or_default()
}
