#!/usr/bin/env bash
# =============================================================================
# Workplace*Memo — scripts/embed-fonts.sh
#
# Reads all .woff2 font files from fonts/ and generates
# src/js/font-data.js containing base64-encoded font data.
#
# This script MUST be run before building for production.
# It is called automatically by `npm run build` (via prebuild hook).
#
# Copyright © 2026 PointSav Digital Systems — EUPL-1.2
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
FONTS_DIR="$PROJECT_DIR/fonts"
OUTPUT="$PROJECT_DIR/src/js/font-data.js"

echo "[embed-fonts] Scanning: $FONTS_DIR"
echo "[embed-fonts] Output:   $OUTPUT"

# ─── Check dependencies ───────────────────────────────────────────────────────

if ! command -v base64 &>/dev/null; then
  echo "[embed-fonts] ERROR: 'base64' command not found." >&2
  exit 1
fi

# ─── Map filename patterns to font metadata ───────────────────────────────────
# Convention: fonts/<FamilyDir>/<Family>-<WeightName>[Italic].woff2
# Weight names → CSS font-weight values

declare -A WEIGHT_MAP=(
  ["Thin"]="100"
  ["ExtraLight"]="200"
  ["Light"]="300"
  ["Regular"]="400"
  ["Medium"]="500"
  ["SemiBold"]="600"
  ["Bold"]="700"
  ["ExtraBold"]="800"
  ["Black"]="900"
  # Variable fonts — fall back to 400
  [""]="400"
)

# ─── Write header ─────────────────────────────────────────────────────────────

cat > "$OUTPUT" << 'HEADER'
/**
 * Workplace*Memo — font-data.js
 *
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: scripts/embed-fonts.sh
 *
 * Contains base64-encoded WOFF2 font data for all built-in font families.
 * All fonts are licensed under SIL Open Font Licence 1.1.
 *
 * Copyright © 2026 PointSav Digital Systems — EUPL-1.2
 */

/* eslint-disable */
window.WORKPLACE_FONT_DATA = {
HEADER

# ─── Process each font family directory ──────────────────────────────────────

FIRST_FAMILY=true

for FAMILY_DIR in "$FONTS_DIR"/*/; do
  [ -d "$FAMILY_DIR" ] || continue
  FAMILY_NAME="$(basename "$FAMILY_DIR")"

  # Skip non-font directories
  [[ "$FAMILY_NAME" == "README.md" ]] && continue

  # Collect .woff2 files for this family
  WOFF2_FILES=("$FAMILY_DIR"*.woff2 2>/dev/null || true)
  [ ${#WOFF2_FILES[@]} -eq 0 ] && {
    echo "[embed-fonts] WARNING: No .woff2 files in $FAMILY_DIR — skipping."
    continue
  }

  echo "[embed-fonts] Processing family: $FAMILY_NAME"

  # Replace hyphens with spaces for CSS font-family value
  CSS_FAMILY="${FAMILY_NAME//-/ }"

  if [ "$FIRST_FAMILY" = false ]; then
    printf ',\n' >> "$OUTPUT"
  fi
  FIRST_FAMILY=false

  printf '  "%s": {\n' "$CSS_FAMILY" >> "$OUTPUT"

  FIRST_WEIGHT=true
  declare -A WRITTEN_WEIGHTS=()

  for WOFF2 in "$FAMILY_DIR"*.woff2; do
    [ -f "$WOFF2" ] || continue
    FILENAME="$(basename "$WOFF2" .woff2)"

    # Determine weight from filename
    CSS_WEIGHT="400"
    for WEIGHT_NAME in "${!WEIGHT_MAP[@]}"; do
      if [[ "$FILENAME" == *"$WEIGHT_NAME"* && -n "$WEIGHT_NAME" ]]; then
        CSS_WEIGHT="${WEIGHT_MAP[$WEIGHT_NAME]}"
        break
      fi
    done

    # Determine style from filename
    CSS_STYLE="normal"
    if [[ "$FILENAME" == *"Italic"* || "$FILENAME" == *"italic"* ]]; then
      CSS_STYLE="italic"
    fi

    echo "[embed-fonts]   $FILENAME → weight:$CSS_WEIGHT style:$CSS_STYLE"

    # Base64-encode the font file
    B64="$(base64 < "$WOFF2" | tr -d '\n')"

    WEIGHT_KEY="${CSS_WEIGHT}"

    if [ "${WRITTEN_WEIGHTS[$WEIGHT_KEY]+_}" ]; then
      # Weight block already started — add style entry
      # (this is a simplified approach; complex families use separate blocks)
      :
    else
      if [ "$FIRST_WEIGHT" = false ]; then
        printf ',\n' >> "$OUTPUT"
      fi
      FIRST_WEIGHT=false
      printf '    "%s": {\n' "$CSS_WEIGHT" >> "$OUTPUT"
      WRITTEN_WEIGHTS[$WEIGHT_KEY]=1
    fi

    printf '      "%s": "%s"\n' "$CSS_STYLE" "$B64" >> "$OUTPUT"
    printf '    }' >> "$OUTPUT"

  done

  # Close the family object
  printf '\n  }' >> "$OUTPUT"

  unset WRITTEN_WEIGHTS
done

# ─── Write footer ─────────────────────────────────────────────────────────────

cat >> "$OUTPUT" << 'FOOTER'

};
FOOTER

echo "[embed-fonts] Done. Output: $OUTPUT"
echo "[embed-fonts] Families embedded: $(grep -c '"[0-9]\{3\}"' "$OUTPUT" || echo 0) weight blocks"
