// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.

//! Dynamic product-catalog renderer for the `/software` storefront page.
//!
//! This module renders the marketplace catalog **from the same [`crate::Catalog`]
//! data that `v1_products` serves** — there is no second source of truth. It replaces
//! the P1 `/software` approach of reading a hand-maintained `software.html` from disk,
//! which drifted from `products.yaml` (the bug this phase fixes: static product cards
//! never reflected catalog changes). Because the cards are generated by iterating the
//! loaded catalog, the page can no longer drift from the data.
//!
//! Rebuilt per `BRIEF-software-hyperscaler-audit.md`'s Licensing Corrections: every
//! catalog entry is now a single [`crate::Installer`] — os-* products only, each with
//! exactly one ratified tier (`license_tier`) and one active price (`price_usdc`).
//! There is no more separate free-installer/license split: `price_usdc == 0` is the
//! active BETA gate (same curl-pipe-sh install as before), and any product's own
//! `license_tier` label (one of `Proprietary`/`FSL-1.1-ALv2`/`AGPL-3.0-or-later`/
//! `Apache-2.0`, per `BRIEF-software-licensing-structure.md`) is always shown
//! regardless of BETA status — that's ratified legal/display metadata, not a
//! payment gate.
//!
//! Fields NOT available in the catalog (noted rather than fabricated):
//!   - **sha256** — no SHA field exists on `Installer`. Per-artifact SHA256 lives on
//!     the release server's per-version `MANIFEST` endpoint (see the install-templates'
//!     verification step), not in `products.yaml`. The badge row therefore shows the
//!     version (`edition`) and `platform`, which ARE present; there is no fabricated
//!     SHA. The copy-to-clipboard affordance (in scope for this phase) is wired to the
//!     install command instead — the load-bearing thing a user actually copies.
//!
//! Pricing units: `price_usdc` is USDC base units (6 decimals), verified against
//! `tool-wallet/src/main.rs` (`$1.00 USDC = 1_000_000 units`). Displayed dollars are
//! `price_usdc as f64 / 1_000_000.0`.

use crate::LicenseTier;
use maud::{html, Markup, PreEscaped};

/// Build the curl-pipe-sh install command for a bare-binary product.
///
/// Matches the pattern established by the install-templates
/// (`app-privategit-source/scripts/install-templates/*.sh`):
/// `curl -fsSL <base>/<id>/install.sh | bash`, where `<base>` is the configured
/// `source_base_url` (default `https://software.pointsav.com/releases`) — the same
/// base `v1_products` uses for `download_url`, so the page and the API agree.
fn install_command(source_base_url: &str, id: &str) -> String {
    let base = source_base_url.trim_end_matches('/');
    format!("curl -fsSL {base}/{id}/install.sh | bash")
}

/// A dark terminal-style install-command block with a copy-to-clipboard button.
/// The button carries the exact command in `data-sw-clip`; the vanilla-JS snippet at
/// the foot of the page copies it. maud escapes the attribute value.
fn install_block(command: &str) -> Markup {
    html! {
        div."sw-cat-install" {
            div."sw-cat-cmd" {
                code."sw-cat-cmd__text" { (command) }
                button."sw-cat-cmd__copy" type="button"
                    data-sw-clip=(command) data-sw-label="Copy"
                    aria-label="Copy install command to clipboard" { "Copy" }
            }
            p."sw-cat-hint" { "Linux x86_64 · verifies SHA256 against the per-version MANIFEST" }
        }
    }
}

/// The tier badge — always shown, regardless of BETA status. Ratified legal/display
/// metadata (factory-release-engineering/LICENSE-MATRIX.md), not a payment gate.
fn tier_badge(tier: LicenseTier) -> Markup {
    html! {
        span."sw-cat-badge sw-cat-badge--tier" { (tier.label()) }
    }
}

/// A free/BETA product card — `price_usdc == 0` (the active BETA gate). Real
/// curl-pipe-sh install command, no payment step, same pattern as before.
///
/// Binary Library Phase 3: the "free" badge text now depends on *why* the price is
/// zero. `Apache`-tier products are permanently free — no BETA gate to ever lift
/// (`load_catalog`'s validation guarantees `price_usdc == 0` is the only legal
/// value for that tier) — so labeling one "BETA" would be a real inaccuracy,
/// implying a future price that will never come. Every other tier keeps the
/// original "BETA · free" wording — per `BRIEF-software-licensing-structure.md`
/// §4, all of them genuinely are in a $0 BETA state with real future pricing yet
/// to be decided, not a placeholder that will never resolve.
fn free_product_card(i: &crate::Installer, source_base_url: &str) -> Markup {
    let command = install_command(source_base_url, &i.id);
    let free_label = if i.license_tier == LicenseTier::Apache {
        "Free \u{00b7} open source"
    } else {
        "BETA \u{00b7} free"
    };
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            h3."sw-cat-card__name" { (i.name) }
            p."sw-cat-card__desc" { (i.description) }
            div."sw-cat-badges" {
                span."sw-cat-badge sw-cat-badge--free" { (free_label) }
                (tier_badge(i.license_tier))
                span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
                span."sw-cat-badge" { (i.platform) }
                span."sw-cat-badge" { (i.size_mb) " MB" }
            }
            (install_block(&command))
        }
    }
}

/// A paid product card — `price_usdc > 0` (BETA lifted for this product). Shows the
/// price and a Polygon-USDC pay CTA.
///
/// Phase 2: the CTA now links to a real, rendered invoice page (`/checkout/:id`)
/// instead of the bare `GET /v1/wallet/address` JSON response — closing the first
/// raw-JSON hop the audit flagged. That JSON endpoint still exists unchanged as
/// the underlying data source; this is just where a human clicking the button lands.
fn paid_product_card(i: &crate::Installer) -> Markup {
    let dollars = i.price_usdc as f64 / 1_000_000.0;
    let checkout_href = format!("/checkout/{}", i.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            h3."sw-cat-card__name" { (i.name) }
            p."sw-cat-card__desc" { (i.description) }
            div."sw-cat-badges" {
                (tier_badge(i.license_tier))
                span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
                span."sw-cat-badge" { (i.platform) }
                span."sw-cat-badge" { (i.size_mb) " MB" }
            }
            div."sw-cat-price" {
                span."sw-cat-price__amt" { "$" (format!("{dollars:.2}")) }
                span."sw-cat-price__unit" { "USDC \u{2014} own it forever, no subscription" }
                div."sw-cat-pay" {
                    a."sw-cat-pay__cta" href=(checkout_href)
                        rel="nofollow" aria-label=(format!("Pay for {} with Polygon USDC", i.name)) {
                        span."sw-cat-pay__mark" aria-hidden="true" { "\u{25C8}" }
                        "Pay with Polygon USDC"
                    }
                    p."sw-cat-pay__meta" { "Polygon PoS \u{00b7} native USDC \u{00b7} a permanent, portable record you hold" }
                }
            }
        }
    }
}

/// Scoped stylesheet for the catalog surface. All selectors are `sw-cat-` prefixed so
/// they never collide with the chrome (`sw-`) or any legacy inline styles. The
/// container width (1280px), horizontal padding (24px), and 768px breakpoint mirror
/// the masthead/footer in `layout.rs` so the grid lines up with the chrome.
fn catalog_style() -> Markup {
    let css = r#".sw-cat-wrap{max-width:1280px;margin:0 auto;padding:40px 24px 64px;box-sizing:border-box;}
.sw-cat-eyebrow{margin:0 0 6px;font-size:12px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:#234ed8;}
.sw-cat-intro{margin:0 0 8px;font-family:Georgia,"Times New Roman",serif;font-size:28px;line-height:1.15;color:#111827;}
.sw-cat-lede{margin:0 0 36px;color:#475467;font-size:15px;line-height:1.55;max-width:64ch;}
.sw-cat-body{display:grid;grid-template-columns:200px 1fr;gap:36px;align-items:start;}
.sw-cat-rail{position:sticky;top:24px;display:flex;flex-direction:column;gap:2px;}
.sw-cat-rail__h{font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:#98a2b3;margin:0 0 8px;}
.sw-cat-rail a{display:flex;justify-content:space-between;gap:8px;padding:7px 10px;border-radius:6px;color:#344054;text-decoration:none;font-size:13.5px;}
.sw-cat-rail a:hover{background:#f2f4f7;}
.sw-cat-rail a.is-current{background:#eef3ff;color:#234ed8;font-weight:600;}
.sw-cat-rail__count{color:#98a2b3;font-size:12px;}
.sw-cat-section{margin:0 0 48px;}
.sw-cat-section__h{display:flex;align-items:baseline;gap:10px;font-size:13px;letter-spacing:.1em;text-transform:uppercase;color:#234ed8;margin:0 0 18px;padding-bottom:8px;border-bottom:2px solid #234ed8;}
.sw-cat-section__count{color:#98a2b3;font-size:11px;letter-spacing:normal;text-transform:none;font-weight:400;}
.sw-cat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px;}
.sw-cat-card{border:1px solid #e4e7ec;border-radius:8px;padding:16px;display:flex;flex-direction:column;background:#fff;transition:border-color .12s ease,box-shadow .12s ease;}
.sw-cat-card:hover{border-color:#b4c5d5;box-shadow:0 2px 8px rgba(22,70,121,.08);}
.sw-cat-card__id{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#667085;letter-spacing:.02em;}
.sw-cat-card__name{font-family:Georgia,"Times New Roman",serif;font-size:17px;line-height:1.2;color:#111827;margin:3px 0 6px;}
.sw-cat-card__desc{font-size:13px;line-height:1.5;color:#475467;margin:0 0 12px;flex:1 0 auto;}
.sw-cat-badges{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 14px;}
.sw-cat-badge{font-size:11px;font-weight:600;letter-spacing:.02em;padding:3px 8px;border-radius:999px;background:#f2f4f7;color:#344054;white-space:nowrap;}
.sw-cat-badge--free{background:#ecfdf3;color:#067647;}
.sw-cat-badge--ver{background:#eef3ff;color:#234ed8;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}
.sw-cat-badge--tier{background:#eef3ff;color:#234ed8;}
.sw-cat-install{margin-top:auto;}
.sw-cat-cmd{display:flex;align-items:stretch;background:#0e1117;border-radius:6px;overflow:hidden;}
.sw-cat-cmd__text{flex:1;color:#e6edf3;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.4;padding:9px 11px;overflow-x:auto;white-space:nowrap;}
.sw-cat-cmd__copy{border:0;background:#234ed8;color:#fff;font-size:11px;font-weight:600;padding:0 14px;cursor:pointer;letter-spacing:.04em;flex:0 0 auto;}
.sw-cat-cmd__copy:hover{background:#173ab1;}
.sw-cat-hint{font-size:11px;color:#98a2b3;margin:7px 0 0;}
.sw-cat-price{margin-top:auto;padding:12px 14px;border:1px solid #e4e7ec;border-radius:6px;background:#f8f9fa;}
.sw-cat-price__amt{font-size:20px;font-weight:700;color:#111827;font-family:Georgia,"Times New Roman",serif;}
.sw-cat-price__unit{font-size:12.5px;color:#667085;margin-left:6px;}
.sw-cat-pay{margin-top:12px;}
.sw-cat-pay__cta{display:inline-flex;align-items:center;justify-content:center;gap:8px;box-sizing:border-box;background:#234ed8;color:#fff;font-size:13px;font-weight:600;letter-spacing:.02em;text-decoration:none;padding:10px 16px;border-radius:6px;border:1px solid #234ed8;transition:background .12s ease;}
.sw-cat-pay__cta:hover{background:#173ab1;border-color:#173ab1;}
.sw-cat-pay__cta:focus-visible{outline:2px solid #234ed8;outline-offset:2px;}
.sw-cat-pay__mark{font-size:14px;line-height:1;}
.sw-cat-pay__meta{margin:8px 0 0;font-size:11.5px;line-height:1.45;color:#667085;}
.sw-cat-shelfsplit{margin:0 0 32px;padding:16px 20px;background:#234ed8;border-radius:8px;}
.sw-cat-shelfsplit__text{max-width:64ch;margin:0 auto;color:#eef3ff;font-size:13px;line-height:1.6;text-align:center;}
.sw-cat-shelf--opensource{margin:0;}
@media (max-width:860px){.sw-cat-body{grid-template-columns:1fr;}.sw-cat-rail{position:static;flex-direction:row;flex-wrap:wrap;gap:8px;}}
@media (max-width:768px){.sw-cat-grid{grid-template-columns:1fr;}.sw-cat-wrap{padding:28px 16px 48px;}.sw-cat-pay__cta{display:flex;width:100%;padding:13px 16px;font-size:14px;}}"#;
    html! { style { (PreEscaped(css)) } }
}

/// Vanilla-JS copy-to-clipboard for every `[data-sw-clip]` control. Explicitly in scope
/// for this phase (unlike P2's broader JS-drawer deferral). Small, dependency-free,
/// and degrades silently where the Clipboard API is unavailable.
fn clipboard_script() -> Markup {
    let js = r#"(function(){
document.querySelectorAll('[data-sw-clip]').forEach(function(btn){
  btn.addEventListener('click',function(){
    var text=btn.getAttribute('data-sw-clip');
    if(!navigator.clipboard){return;}
    navigator.clipboard.writeText(text).then(function(){
      var label=btn.getAttribute('data-sw-label')||btn.textContent;
      btn.textContent='Copied';
      setTimeout(function(){btn.textContent=label;},1500);
    }).catch(function(){});
  });
});
})();"#;
    html! { script { (PreEscaped(js)) } }
}

/// Render the full product catalog as body content for the `/software` page.
///
/// **Redesigned 2026-07-07** away from the near-black/gold "Sovereign Editorial"
/// visual system (verified, per `tokens.rs`'s doc comment, to not actually match
/// any real PointSav/Woodfine property) toward a denser, marketplace-style layout
/// — a left category rail plus a wider card grid — while keeping the family's real,
/// verified colors (navy `#234ed8` as the one accent, `Georgia`/serif matching the
/// family's `Source Serif 4` fallback, no gold).
///
/// Iterates the loaded [`crate::Catalog`] (the same struct `v1_products` serves), grouped
/// two ways at once:
///
/// 1. **Shelf** (`LicenseTier::shelf`, `BRIEF-binary-library-repositioning.md`'s two-shelf
///    model, operator-approved 2026-07-07) — the outer grouping. `Proprietary`/`Fsl`/`Agpl`
///    tiers render inside the **Commercial** shelf (the ratified os-*-only public catalog).
///    `Apache` tier renders inside a separate **Open Source / Community** shelf — same
///    neutral surface as the Commercial shelf (no background-color coding since gold is
///    gone), distinguished by its own section heading and navy tier badges, same as
///    everywhere else. Only rendered when at least one `apache`-tier product exists in the
///    catalog.
/// 2. **Tier** (within the Commercial shelf) — `Proprietary`, `FSL-1.1-ALv2`, and
///    `AGPL-3.0-or-later` each keep their own named section, matching
///    `BRIEF-software-licensing-structure.md`'s per-product table exactly (rebuilt
///    2026-07-07 — that BRIEF's table never uses "PointSav Commercial" as a tier; see
///    `LicenseTier`'s doc comment in `main.rs` for the full per-product mapping and the
///    reasoning). Each product still renders its own BETA-free-vs-paid card individually
///    (`free_product_card`/`paid_product_card`).
///
/// The left rail's categories are exactly the two real shelves — no invented product
/// taxonomy (the CURSOR-marketplace mockup this design takes structural cues from used
/// lifecycle-phase categories that don't correspond to anything in PointSav's actual
/// data model; inventing an equivalent here would be decoration, not information).
///
/// The returned [`Markup`] is meant to be wrapped by `layout::render_page`, which supplies
/// the masthead + footer chrome.
pub fn catalog_markup(catalog: &crate::Catalog, source_base_url: &str) -> Markup {
    let proprietary: Vec<_> = catalog
        .installers
        .iter()
        .filter(|i| i.license_tier == LicenseTier::Proprietary)
        .collect();
    let fsl: Vec<_> = catalog
        .installers
        .iter()
        .filter(|i| i.license_tier == LicenseTier::Fsl)
        .collect();
    let agpl: Vec<_> = catalog
        .installers
        .iter()
        .filter(|i| i.license_tier == LicenseTier::Agpl)
        .collect();
    let apache: Vec<_> = catalog
        .installers
        .iter()
        .filter(|i| i.license_tier == LicenseTier::Apache)
        .collect();
    let commercial_count = proprietary.len() + fsl.len() + agpl.len();
    let total_count = catalog.installers.len();

    let tier_section = |id: &'static str, heading: &'static str, products: &[&crate::Installer]| {
        html! {
            @if !products.is_empty() {
                section."sw-cat-section" id=(id) {
                    h2."sw-cat-section__h" {
                        (heading)
                        span."sw-cat-section__count" { (products.len()) }
                    }
                    div."sw-cat-grid" {
                        @for i in products {
                            @if i.price_usdc == 0 {
                                (free_product_card(i, source_base_url))
                            } @else {
                                (paid_product_card(i))
                            }
                        }
                    }
                }
            }
        }
    };

    html! {
        (catalog_style())
        div."sw-cat-wrap" {
            p."sw-cat-eyebrow" { "The Binary Library" }
            h1."sw-cat-intro" { "Products" }
            p."sw-cat-lede" {
                "Buy it once. Run it anywhere. Own it forever. No subscription, no cloud \
                 dependency, no kill switch. Buying your first component here is also your \
                 key to the rest of the stack\u{2014}the components of an orchestration, not \
                 an app store. This catalog is rendered directly from the release catalog\
                 \u{2014}what you see here is exactly what the download API serves."
            }
            div."sw-cat-body" {
                nav."sw-cat-rail" aria-label="Catalog shelves" {
                    p."sw-cat-rail__h" { "Shelves" }
                    a href="#commercial" {
                        "Commercial" span."sw-cat-rail__count" { (commercial_count) }
                    }
                    @if !apache.is_empty() {
                        a href="#open-source" {
                            "Open Source / Community" span."sw-cat-rail__count" { (apache.len()) }
                        }
                    }
                    a href="/software" class="is-current" {
                        "All products" span."sw-cat-rail__count" { (total_count) }
                    }
                }
                div."sw-cat-main" {
                    div."sw-cat-shelf sw-cat-shelf--commercial" {
                        (tier_section("proprietary", "Proprietary", &proprietary))
                        (tier_section("fsl", "FSL-1.1-ALv2", &fsl))
                        (tier_section("agpl", "AGPL-3.0-or-later", &agpl))
                    }
                    @if !apache.is_empty() {
                        div."sw-cat-shelfsplit" {
                            p."sw-cat-shelfsplit__text" {
                                "Two shelves, one catalog. The Commercial shelf above is the ratified, \
                                 paid-or-BETA os-* product line. The Open Source shelf below lists \
                                 components that have been relicensed to a genuine, unconditional \
                                 Apache-2.0 grant\u{2014}free permanently, not a BETA gate awaiting a \
                                 future price."
                            }
                        }
                        div."sw-cat-shelf sw-cat-shelf--opensource" {
                            (tier_section("open-source", "Open Source \u{00b7} Community", &apache))
                        }
                    }
                }
            }
        }
        (clipboard_script())
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────
//
// Pure rendering functions — no server, no filesystem, no network.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Catalog, Installer};

    const BASE: &str = "https://example.invalid/releases";

    fn fixture() -> Catalog {
        Catalog {
            installers: vec![
                Installer {
                    id: "os-mediakit".into(),
                    name: "MediaKit OS".into(),
                    description: "Sovereign media workstation image.".into(),
                    edition: "1.2.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 812,
                    path: "os-mediakit/1.2.0/installer.run".into(),
                    license_tier: LicenseTier::Fsl,
                    price_usdc: 0, // active BETA gate
                    fsl_conversion_date: None,
                    guide_url: None,
                },
                Installer {
                    id: "os-console".into(),
                    name: "Console OS".into(),
                    description: "Operator Terminal Surface.".into(),
                    edition: "1.0.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 150,
                    path: "os-console/1.0.0/installer.run".into(),
                    license_tier: LicenseTier::Agpl,
                    price_usdc: 19_000_000, // BETA lifted, test fixture only ($19)
                    fsl_conversion_date: None,
                    guide_url: None,
                },
            ],
        }
    }

    #[test]
    fn install_command_shape_and_trailing_slash_handling() {
        assert_eq!(
            install_command(BASE, "os-mediakit"),
            "curl -fsSL https://example.invalid/releases/os-mediakit/install.sh | bash"
        );
        // A trailing slash on the configured base must not produce a double slash.
        assert_eq!(
            install_command("https://example.invalid/releases/", "x"),
            "curl -fsSL https://example.invalid/releases/x/install.sh | bash"
        );
    }

    #[test]
    fn known_products_appear_in_rendered_markup() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // Known ids and names from the fixture drive the cards (no drift possible).
        assert!(html.contains("os-mediakit"));
        assert!(html.contains("MediaKit OS"));
        assert!(html.contains("os-console"));
        assert!(html.contains("Console OS"));
        assert!(html.contains("FSL-1.1-ALv2"));
        assert!(html.contains("AGPL-3.0-or-later"));
        assert!(
            !html.contains("Apache 2.0<") && !html.contains("PointSav Commercial"),
            "must not use a factually wrong or retired tier label"
        );
        // Each populated tier renders its own section (Phase 3: grouped by license
        // tier, not by free/paid — os-mediakit is FSL, os-console is AGPL).
        assert!(html.contains(r#"id="agpl""#));
        assert!(html.contains(r#"id="fsl""#));
        // Section heading contains the tier name plus a live product count (added
        // 2026-07-07 redesign) — check the open tag + heading text, not an exact
        // closing match, since a `<span class="sw-cat-section__count">` now sits
        // between the heading text and `</h2>`.
        assert!(html.contains("<h2 class=\"sw-cat-section__h\">AGPL-3.0-or-later"));
        assert!(html.contains("<h2 class=\"sw-cat-section__h\">FSL-1.1-ALv2"));
        // Badge row shows the fields that ARE in the catalog.
        assert!(html.contains("v1.2.0"));
        assert!(html.contains("linux-x86_64"));
        assert!(html.contains("812 MB"));
    }

    #[test]
    fn paid_product_renders_pricing_cta_and_no_install_command() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // Non-zero price_usdc -> price display + Polygon USDC CTA.
        assert!(html.contains("$19.00"));
        assert!(html.contains("Pay with Polygon USDC"));
        assert!(html.contains("href=\"/checkout/os-console\""));
        // And NO curl-pipe-sh install command for the paid product.
        assert!(
            !html.contains("releases/os-console/install.sh"),
            "paid product must NOT render an install command"
        );
    }

    #[test]
    fn free_products_render_curl_install_commands() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // price_usdc == 0 -> BETA/free, real curl-pipe-sh command with the right id.
        assert!(html
            .contains("curl -fsSL https://example.invalid/releases/os-mediakit/install.sh | bash"));
        assert!(html.contains("BETA · free"));
        // The copy affordance carries the exact command.
        assert!(html.contains("data-sw-clip"));
    }

    #[test]
    fn empty_catalog_renders_shell_without_sections() {
        let empty = Catalog { installers: vec![] };
        let html = catalog_markup(&empty, BASE).into_string();
        // Page shell still renders…
        assert!(html.contains("sw-cat-intro"));
        // …but no product section.
        assert!(!html.contains("id=\"proprietary\""));
        assert!(!html.contains("id=\"fsl\""));
        assert!(!html.contains("id=\"agpl\""));
        assert!(!html.contains("id=\"open-source\""));
    }

    #[test]
    fn products_are_grouped_by_tier_not_by_prefix_family() {
        // Regression guard for Phase 3: the catalog only ever models os-* installers
        // (tool-wallet, app-*, soft-* never reach this struct at all — they were
        // removed from products.yaml in Phase 1), and cards are grouped by
        // `license_tier`, never by an id-prefix family grid.
        let html = catalog_markup(&fixture(), BASE).into_string();
        assert!(!html.contains("tool-wallet"));
        assert!(!html.contains("Wallet &amp; Tools"));
        assert!(!html.contains("Knowledge &amp; Source"));
        assert!(!html.contains("Orchestration"));
    }

    // ── Binary Library Phase 3: two-shelf model ───────────────────────────────
    // (BRIEF-binary-library-repositioning.md, operator-approved 2026-07-07)

    fn fixture_with_open_source() -> Catalog {
        let mut catalog = fixture();
        catalog.installers.push(Installer {
            id: "tool-wallet".into(),
            name: "PointSav Wallet".into(),
            description: "Polygon USDC watcher, relicensed Apache-2.0.".into(),
            edition: "1.0.0".into(),
            platform: "linux-x86_64".into(),
            size_mb: 12,
            path: "tool-wallet/1.0.0/installer.run".into(),
            license_tier: LicenseTier::Apache,
            price_usdc: 0,
            fsl_conversion_date: None,
            guide_url: None,
        });
        catalog
    }

    #[test]
    fn open_source_tier_renders_in_distinct_shelf_section() {
        let html = catalog_markup(&fixture_with_open_source(), BASE).into_string();
        // Own section, own id — never folded into "FSL" (the pre-Phase-3 2-way
        // partition would have silently misfiled Apache under the FSL heading).
        assert!(html.contains(r#"id="open-source""#));
        assert!(html.contains("Open Source"));
        assert!(html.contains("Community"));
        assert!(html.contains("tool-wallet"));
        assert!(html.contains("Apache-2.0 (Open Source)"));
        // The two-shelf explainer strip appears whenever the shelf does. Check the
        // rendered *element* (class attribute + its text), not just the class name —
        // the CSS class selector of the same name is always present in the
        // stylesheet regardless of whether the element itself renders.
        assert!(html.contains(r#"class="sw-cat-shelfsplit""#));
        assert!(html.contains("Two shelves, one catalog"));
        // Distinct shelf CSS scope, not reusing the Commercial shelf's classes.
        assert!(html.contains(r#"class="sw-cat-shelf sw-cat-shelf--opensource""#));
    }

    #[test]
    fn open_source_shelf_absent_when_no_open_source_products() {
        // The base fixture has zero OpenSource-tier installers (matches the live
        // catalog today — Phase 2 landed governance, not a real catalog entry).
        // Check for the rendered *element* class attribute, not the bare class name
        // — the stylesheet always defines `.sw-cat-shelfsplit`/`.sw-cat-shelf--
        // opensource` regardless of whether either element actually renders, so a
        // bare substring check would pass even if this regressed to always-render.
        let html = catalog_markup(&fixture(), BASE).into_string();
        assert!(!html.contains(r#"id="open-source""#));
        assert!(!html.contains(r#"class="sw-cat-shelfsplit""#));
        assert!(!html.contains(r#"class="sw-cat-shelf sw-cat-shelf--opensource""#));
        assert!(!html.contains("Two shelves, one catalog"));
    }

    #[test]
    fn open_source_free_badge_reads_open_source_not_beta() {
        // A permanently-free Apache-2.0 grant is not a "BETA" gate awaiting a future
        // price (Phase 1's `load_catalog` guarantees `price_usdc == 0` is the only
        // legal value here) — the badge copy must not imply one.
        let html = catalog_markup(&fixture_with_open_source(), BASE).into_string();
        assert!(html.contains("Free \u{00b7} open source"));
        // The existing FSL/AGPL fixture items still say "BETA · free" —
        // unaffected by the Apache-specific badge text.
        assert!(html.contains("BETA \u{00b7} free"));
    }

    #[test]
    fn hero_introduces_the_binary_library_without_replacing_established_copy() {
        // Binary Library Phase 4: a small eyebrow label names the concept; the
        // established, already-shipped "buy it once… own it forever" lede is
        // extended, not replaced (that copy is referenced/tested elsewhere and is
        // load-bearing brand voice, not a placeholder to discard).
        let html = catalog_markup(&fixture(), BASE).into_string();
        assert!(html.contains("The Binary Library"));
        assert!(html.contains("Buy it once. Run it anywhere. Own it forever."));
        assert!(html.contains("components of an orchestration, not"));
        assert!(html.contains("an app store"));
    }
}
