//! Dynamic product-catalog renderer for the `/software` storefront page.
//!
//! This module renders the marketplace catalog **from the same [`crate::Catalog`]
//! data that `v1_products` serves** — there is no second source of truth. It replaces
//! the P1 `/software` approach of reading a hand-maintained `software.html` from disk,
//! which drifted from `products.yaml` (the bug this phase fixes: static product cards
//! never reflected catalog changes). Because the cards are generated by iterating the
//! loaded catalog, the page can no longer drift from the data.
//!
//! Catalog fields available and how they map to the card:
//!   - [`crate::Installer`]: `id`, `name`, `description`, `edition` (used as the
//!     version badge), `platform`, `size_mb`, `path`. Installers are always free —
//!     each renders a real curl-pipe-sh install command.
//!   - [`crate::License`]: `id`, `name`, `description`, `module_tag`, `price_usdc`.
//!     `price_usdc == 0` → BETA/free (curl-pipe-sh install, same pattern). Non-zero
//!     → paid tier: price display plus a "Pay with Polygon USDC" CTA (P4). The CTA is
//!     display + navigation only — it links to `/v1/wallet/address` (the payment
//!     descriptor); a live wallet-connect browser interaction is out of scope here.
//!
//! Fields NOT available in the catalog (noted rather than fabricated):
//!   - **sha256** — no SHA field exists on either struct. Per-artifact SHA256 lives on
//!     the release server's per-version `MANIFEST` endpoint (see the install-templates'
//!     verification step), not in `products.yaml`. The badge row therefore shows the
//!     version (`edition`) and `platform`, which ARE present; there is no fabricated
//!     SHA. The copy-to-clipboard affordance (in scope for this phase) is wired to the
//!     install command instead — the load-bearing thing a user actually copies.
//!
//! Pricing units: `price_usdc` is USDC base units (6 decimals), verified against
//! `tool-wallet/src/main.rs` (`$1.00 USDC = 1_000_000 units`). Displayed dollars are
//! `price_usdc as f64 / 1_000_000.0`.

use maud::{html, Markup, PreEscaped};

/// Build the curl-pipe-sh install command for a bare-binary product.
///
/// Matches the pattern established by the install-templates
/// (`app-privategit-source/scripts/install-templates/*.sh`):
/// `curl -fsSL <base>/<id>/install.sh | bash`, where `<base>` is the configured
/// `source_base_url` (default `https://software.pointsav.com/releases`) — the same
/// base `v1_products` uses for `download_url`, so the page and the API agree.
fn install_command(source_base_url: &str, id: &str) -> String {
    let base = source_base_url.trim_end_matches('/');
    format!("curl -fsSL {base}/{id}/install.sh | bash")
}

/// A dark terminal-style install-command block with a copy-to-clipboard button.
/// The button carries the exact command in `data-sw-clip`; the vanilla-JS snippet at
/// the foot of the page copies it. maud escapes the attribute value.
fn install_block(command: &str) -> Markup {
    html! {
        div."sw-cat-install" {
            div."sw-cat-cmd" {
                code."sw-cat-cmd__text" { (command) }
                button."sw-cat-cmd__copy" type="button"
                    data-sw-clip=(command) data-sw-label="Copy"
                    aria-label="Copy install command to clipboard" { "Copy" }
            }
            p."sw-cat-hint" { "Linux x86_64 · verifies SHA256 against the per-version MANIFEST" }
        }
    }
}

/// A single installer card (always free — curl-pipe-sh install).
fn installer_card(i: &crate::Installer, source_base_url: &str) -> Markup {
    let command = install_command(source_base_url, &i.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            h3."sw-cat-card__name" { (i.name) }
            p."sw-cat-card__desc" { (i.description) }
            div."sw-cat-badges" {
                span."sw-cat-badge sw-cat-badge--free" { "Free" }
                span."sw-cat-badge" { "Installer" }
                // version — `edition` is present in the catalog; SHA is not (see module docs).
                span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
                span."sw-cat-badge" { (i.platform) }
                span."sw-cat-badge" { (i.size_mb) " MB" }
            }
            (install_block(&command))
        }
    }
}

/// A free (BETA) license/module card — `price_usdc == 0`. Same curl-pipe-sh install
/// pattern as installers.
fn free_license_card(l: &crate::License, source_base_url: &str) -> Markup {
    let command = install_command(source_base_url, &l.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (l.id) }
            h3."sw-cat-card__name" { (l.name) }
            p."sw-cat-card__desc" { (l.description) }
            div."sw-cat-badges" {
                span."sw-cat-badge sw-cat-badge--free" { "BETA \u{00b7} free" }
                @if !l.module_tag.is_empty() {
                    span."sw-cat-badge sw-cat-badge--ver" { (l.module_tag) }
                }
            }
            (install_block(&command))
        }
    }
}

/// A paid license-tier card — `price_usdc > 0`. Shows the price and a Polygon-USDC
/// pay CTA.
///
/// P4 scope: the CTA is **display + navigation only**. It links to `/v1/wallet/address`
/// (the JSON descriptor of the receiving wallet, chain, token, and USDC contract) so a
/// buyer can retrieve the exact on-chain payment target. Wiring a live "connect wallet"
/// browser-extension interaction is deliberately NOT done here — that would require a
/// wallet-connect library dependency, which is out of scope for this phase. The button
/// degrades to a plain link and is full-width on narrow viewports (see `catalog_style`).
fn paid_license_card(l: &crate::License) -> Markup {
    let dollars = l.price_usdc as f64 / 1_000_000.0;
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (l.id) }
            h3."sw-cat-card__name" { (l.name) }
            p."sw-cat-card__desc" { (l.description) }
            div."sw-cat-badges" {
                span."sw-cat-badge" { "License tier" }
                @if !l.module_tag.is_empty() {
                    span."sw-cat-badge sw-cat-badge--ver" { (l.module_tag) }
                }
            }
            div."sw-cat-price" {
                span."sw-cat-price__amt" { "$" (format!("{dollars:.2}")) }
                span."sw-cat-price__unit" { "USDC \u{2014} license required" }
                div."sw-cat-pay" {
                    a."sw-cat-pay__cta" href="/v1/wallet/address"
                        rel="nofollow" aria-label=(format!("Pay for {} with Polygon USDC", l.name)) {
                        span."sw-cat-pay__mark" aria-hidden="true" { "\u{25C8}" }
                        "Pay with Polygon USDC"
                    }
                    p."sw-cat-pay__meta" { "Polygon PoS \u{00b7} native USDC \u{00b7} verify your transaction to receive a license key" }
                }
            }
        }
    }
}

/// Scoped stylesheet for the catalog surface. All selectors are `sw-cat-` prefixed so
/// they never collide with the chrome (`sw-`) or any legacy inline styles. The
/// container width (1280px), horizontal padding (24px), and 768px breakpoint mirror
/// the masthead/footer in `layout.rs` so the grid lines up with the chrome.
fn catalog_style() -> Markup {
    let css = r#".sw-cat-wrap{max-width:1280px;margin:0 auto;padding:40px 24px 64px;box-sizing:border-box;}
.sw-cat-intro{margin:0 0 8px;font-family:"Playfair Display",Georgia,serif;font-size:28px;line-height:1.15;color:#111;}
.sw-cat-lede{margin:0 0 36px;color:#475467;font-size:15px;line-height:1.55;max-width:64ch;}
.sw-cat-section{margin:0 0 48px;}
.sw-cat-section__h{font-size:13px;letter-spacing:.14em;text-transform:uppercase;color:#164679;margin:0 0 18px;padding-bottom:8px;border-bottom:2px solid #C7A961;}
.sw-cat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px;}
.sw-cat-card{border:1px solid #e4e7ec;border-radius:10px;padding:20px;display:flex;flex-direction:column;background:#fff;box-shadow:0 1px 2px rgba(16,24,40,.04);}
.sw-cat-card__id{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#667085;letter-spacing:.02em;}
.sw-cat-card__name{font-family:"Playfair Display",Georgia,serif;font-size:19px;line-height:1.2;color:#111;margin:4px 0 8px;}
.sw-cat-card__desc{font-size:13.5px;line-height:1.55;color:#475467;margin:0 0 16px;flex:1 0 auto;}
.sw-cat-badges{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 16px;}
.sw-cat-badge{font-size:11px;font-weight:600;letter-spacing:.02em;padding:3px 8px;border-radius:999px;background:#f2f4f7;color:#344054;white-space:nowrap;}
.sw-cat-badge--free{background:#ecfdf3;color:#067647;}
.sw-cat-badge--ver{background:#eff4ff;color:#164679;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}
.sw-cat-install{margin-top:auto;}
.sw-cat-cmd{display:flex;align-items:stretch;background:#0e1117;border-radius:8px;overflow:hidden;}
.sw-cat-cmd__text{flex:1;color:#e6edf3;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.4;padding:10px 12px;overflow-x:auto;white-space:nowrap;}
.sw-cat-cmd__copy{border:0;background:#164679;color:#fff;font-size:11px;font-weight:600;padding:0 14px;cursor:pointer;letter-spacing:.04em;flex:0 0 auto;}
.sw-cat-cmd__copy:hover{background:#C7A961;color:#111;}
.sw-cat-hint{font-size:11px;color:#98a2b3;margin:8px 0 0;}
.sw-cat-price{margin-top:auto;padding:14px 16px;border:1px dashed #d0d5dd;border-radius:8px;background:#fcfcfd;}
.sw-cat-price__amt{font-size:22px;font-weight:700;color:#111;font-family:"Playfair Display",Georgia,serif;}
.sw-cat-price__unit{font-size:13px;color:#667085;margin-left:6px;}
.sw-cat-pay{margin-top:12px;}
.sw-cat-pay__cta{display:inline-flex;align-items:center;justify-content:center;gap:8px;box-sizing:border-box;background:#6c4cf1;color:#fff;font-size:13px;font-weight:600;letter-spacing:.02em;text-decoration:none;padding:10px 16px;border-radius:8px;border:1px solid #5a3fd6;transition:background .12s ease;}
.sw-cat-pay__cta:hover{background:#5a3fd6;}
.sw-cat-pay__cta:focus-visible{outline:2px solid #164679;outline-offset:2px;}
.sw-cat-pay__mark{font-size:14px;line-height:1;}
.sw-cat-pay__meta{margin:8px 0 0;font-size:11.5px;line-height:1.45;color:#667085;}
@media (max-width:768px){.sw-cat-grid{grid-template-columns:1fr;}.sw-cat-wrap{padding:28px 16px 48px;}.sw-cat-pay__cta{display:flex;width:100%;padding:13px 16px;font-size:14px;}}"#;
    html! { style { (PreEscaped(css)) } }
}

/// Vanilla-JS copy-to-clipboard for every `[data-sw-clip]` control. Explicitly in scope
/// for this phase (unlike P2's broader JS-drawer deferral). Small, dependency-free,
/// and degrades silently where the Clipboard API is unavailable.
fn clipboard_script() -> Markup {
    let js = r#"(function(){
document.querySelectorAll('[data-sw-clip]').forEach(function(btn){
  btn.addEventListener('click',function(){
    var text=btn.getAttribute('data-sw-clip');
    if(!navigator.clipboard){return;}
    navigator.clipboard.writeText(text).then(function(){
      var label=btn.getAttribute('data-sw-label')||btn.textContent;
      btn.textContent='Copied';
      setTimeout(function(){btn.textContent=label;},1500);
    }).catch(function(){});
  });
});
})();"#;
    html! { script { (PreEscaped(js)) } }
}

/// Render the full product catalog as body content for the `/software` page.
///
/// Iterates the loaded [`crate::Catalog`] (the same struct `v1_products` serves):
/// installers first, then licenses split into free (BETA) and paid tiers. The returned
/// [`Markup`] is meant to be wrapped by `layout::render_page`, which supplies the
/// Sovereign Editorial masthead + footer chrome.
pub fn catalog_markup(catalog: &crate::Catalog, source_base_url: &str) -> Markup {
    let (free_licenses, paid_licenses): (Vec<_>, Vec<_>) =
        catalog.licenses.iter().partition(|l| l.price_usdc == 0);

    html! {
        (catalog_style())
        div."sw-cat-wrap" {
            h1."sw-cat-intro" { "Products" }
            p."sw-cat-lede" {
                "Sovereign binary distribution for the PointSav platform. Installers and \
                 BETA modules install with a single verified command; licensed tiers list \
                 their current price. This catalog is rendered directly from the release \
                 catalog\u{2014}what you see here is exactly what the download API serves."
            }

            @if !catalog.installers.is_empty() {
                section."sw-cat-section" id="installers" {
                    h2."sw-cat-section__h" { "Operating systems & installers" }
                    div."sw-cat-grid" {
                        @for i in &catalog.installers {
                            (installer_card(i, source_base_url))
                        }
                    }
                }
            }

            @if !free_licenses.is_empty() {
                section."sw-cat-section" id="downloads" {
                    h2."sw-cat-section__h" { "Platform modules \u{2014} BETA (free)" }
                    div."sw-cat-grid" {
                        @for l in &free_licenses {
                            (free_license_card(l, source_base_url))
                        }
                    }
                }
            }

            @if !paid_licenses.is_empty() {
                section."sw-cat-section" id="licensing" {
                    h2."sw-cat-section__h" { "License tiers" }
                    div."sw-cat-grid" {
                        @for l in &paid_licenses {
                            (paid_license_card(l))
                        }
                    }
                }
            }
        }
        (clipboard_script())
    }
}
