//! Dynamic product-catalog renderer for the `/software` storefront page.
//!
//! This module renders the marketplace catalog **from the same [`crate::Catalog`]
//! data that `v1_products` serves** — there is no second source of truth. It replaces
//! the P1 `/software` approach of reading a hand-maintained `software.html` from disk,
//! which drifted from `products.yaml` (the bug this phase fixes: static product cards
//! never reflected catalog changes). Because the cards are generated by iterating the
//! loaded catalog, the page can no longer drift from the data.
//!
//! Rebuilt per `BRIEF-software-hyperscaler-audit.md`'s Licensing Corrections: every
//! catalog entry is now a single [`crate::Installer`] — os-* products only, each with
//! exactly one ratified tier (`license_tier`) and one active price (`price_usdc`).
//! There is no more separate free-installer/license split: `price_usdc == 0` is the
//! active BETA gate (same curl-pipe-sh install as before), and any product's own
//! `license_tier` label ("PointSav Commercial" or "FSL") is always shown regardless of
//! BETA status — that's ratified legal/display metadata, not a payment gate.
//!
//! Fields NOT available in the catalog (noted rather than fabricated):
//!   - **sha256** — no SHA field exists on `Installer`. Per-artifact SHA256 lives on
//!     the release server's per-version `MANIFEST` endpoint (see the install-templates'
//!     verification step), not in `products.yaml`. The badge row therefore shows the
//!     version (`edition`) and `platform`, which ARE present; there is no fabricated
//!     SHA. The copy-to-clipboard affordance (in scope for this phase) is wired to the
//!     install command instead — the load-bearing thing a user actually copies.
//!
//! Pricing units: `price_usdc` is USDC base units (6 decimals), verified against
//! `tool-wallet/src/main.rs` (`$1.00 USDC = 1_000_000 units`). Displayed dollars are
//! `price_usdc as f64 / 1_000_000.0`.

use crate::LicenseTier;
use maud::{html, Markup, PreEscaped};

/// Build the curl-pipe-sh install command for a bare-binary product.
///
/// Matches the pattern established by the install-templates
/// (`app-privategit-source/scripts/install-templates/*.sh`):
/// `curl -fsSL <base>/<id>/install.sh | bash`, where `<base>` is the configured
/// `source_base_url` (default `https://software.pointsav.com/releases`) — the same
/// base `v1_products` uses for `download_url`, so the page and the API agree.
fn install_command(source_base_url: &str, id: &str) -> String {
    let base = source_base_url.trim_end_matches('/');
    format!("curl -fsSL {base}/{id}/install.sh | bash")
}

/// A dark terminal-style install-command block with a copy-to-clipboard button.
/// The button carries the exact command in `data-sw-clip`; the vanilla-JS snippet at
/// the foot of the page copies it. maud escapes the attribute value.
fn install_block(command: &str) -> Markup {
    html! {
        div."sw-cat-install" {
            div."sw-cat-cmd" {
                code."sw-cat-cmd__text" { (command) }
                button."sw-cat-cmd__copy" type="button"
                    data-sw-clip=(command) data-sw-label="Copy"
                    aria-label="Copy install command to clipboard" { "Copy" }
            }
            p."sw-cat-hint" { "Linux x86_64 · verifies SHA256 against the per-version MANIFEST" }
        }
    }
}

/// The tier badge — always shown, regardless of BETA status. Ratified legal/display
/// metadata (factory-release-engineering/LICENSE-MATRIX.md), not a payment gate.
fn tier_badge(tier: LicenseTier) -> Markup {
    html! {
        span."sw-cat-badge sw-cat-badge--tier" { (tier.label()) }
    }
}

/// A free/BETA product card — `price_usdc == 0` (the active BETA gate). Real
/// curl-pipe-sh install command, no payment step, same pattern as before.
fn free_product_card(i: &crate::Installer, source_base_url: &str) -> Markup {
    let command = install_command(source_base_url, &i.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            h3."sw-cat-card__name" { (i.name) }
            p."sw-cat-card__desc" { (i.description) }
            div."sw-cat-badges" {
                span."sw-cat-badge sw-cat-badge--free" { "BETA \u{00b7} free" }
                (tier_badge(i.license_tier))
                span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
                span."sw-cat-badge" { (i.platform) }
                span."sw-cat-badge" { (i.size_mb) " MB" }
            }
            (install_block(&command))
        }
    }
}

/// A paid product card — `price_usdc > 0` (BETA lifted for this product). Shows the
/// price and a Polygon-USDC pay CTA.
///
/// Phase 2: the CTA now links to a real, rendered invoice page (`/checkout/:id`)
/// instead of the bare `GET /v1/wallet/address` JSON response — closing the first
/// raw-JSON hop the audit flagged. That JSON endpoint still exists unchanged as
/// the underlying data source; this is just where a human clicking the button lands.
fn paid_product_card(i: &crate::Installer) -> Markup {
    let dollars = i.price_usdc as f64 / 1_000_000.0;
    let checkout_href = format!("/checkout/{}", i.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            h3."sw-cat-card__name" { (i.name) }
            p."sw-cat-card__desc" { (i.description) }
            div."sw-cat-badges" {
                (tier_badge(i.license_tier))
                span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
                span."sw-cat-badge" { (i.platform) }
                span."sw-cat-badge" { (i.size_mb) " MB" }
            }
            div."sw-cat-price" {
                span."sw-cat-price__amt" { "$" (format!("{dollars:.2}")) }
                span."sw-cat-price__unit" { "USDC \u{2014} own it forever, no subscription" }
                div."sw-cat-pay" {
                    a."sw-cat-pay__cta" href=(checkout_href)
                        rel="nofollow" aria-label=(format!("Pay for {} with Polygon USDC", i.name)) {
                        span."sw-cat-pay__mark" aria-hidden="true" { "\u{25C8}" }
                        "Pay with Polygon USDC"
                    }
                    p."sw-cat-pay__meta" { "Polygon PoS \u{00b7} native USDC \u{00b7} a permanent, portable record you hold" }
                }
            }
        }
    }
}

/// Scoped stylesheet for the catalog surface. All selectors are `sw-cat-` prefixed so
/// they never collide with the chrome (`sw-`) or any legacy inline styles. The
/// container width (1280px), horizontal padding (24px), and 768px breakpoint mirror
/// the masthead/footer in `layout.rs` so the grid lines up with the chrome.
fn catalog_style() -> Markup {
    let css = r#".sw-cat-wrap{max-width:1280px;margin:0 auto;padding:40px 24px 64px;box-sizing:border-box;}
.sw-cat-intro{margin:0 0 8px;font-family:"Playfair Display",Georgia,serif;font-size:28px;line-height:1.15;color:#111;}
.sw-cat-lede{margin:0 0 36px;color:#475467;font-size:15px;line-height:1.55;max-width:64ch;}
.sw-cat-section{margin:0 0 48px;}
.sw-cat-section__h{font-size:13px;letter-spacing:.14em;text-transform:uppercase;color:#164679;margin:0 0 18px;padding-bottom:8px;border-bottom:2px solid #C7A961;}
.sw-cat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px;}
.sw-cat-card{border:1px solid #e4e7ec;border-radius:10px;padding:20px;display:flex;flex-direction:column;background:#fff;box-shadow:0 1px 2px rgba(16,24,40,.04);}
.sw-cat-card__id{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#667085;letter-spacing:.02em;}
.sw-cat-card__name{font-family:"Playfair Display",Georgia,serif;font-size:19px;line-height:1.2;color:#111;margin:4px 0 8px;}
.sw-cat-card__desc{font-size:13.5px;line-height:1.55;color:#475467;margin:0 0 16px;flex:1 0 auto;}
.sw-cat-badges{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 16px;}
.sw-cat-badge{font-size:11px;font-weight:600;letter-spacing:.02em;padding:3px 8px;border-radius:999px;background:#f2f4f7;color:#344054;white-space:nowrap;}
.sw-cat-badge--free{background:#ecfdf3;color:#067647;}
.sw-cat-badge--ver{background:#eff4ff;color:#164679;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}
.sw-cat-badge--tier{background:#fdf2e9;color:#8a4b13;}
.sw-cat-install{margin-top:auto;}
.sw-cat-cmd{display:flex;align-items:stretch;background:#0e1117;border-radius:8px;overflow:hidden;}
.sw-cat-cmd__text{flex:1;color:#e6edf3;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.4;padding:10px 12px;overflow-x:auto;white-space:nowrap;}
.sw-cat-cmd__copy{border:0;background:#164679;color:#fff;font-size:11px;font-weight:600;padding:0 14px;cursor:pointer;letter-spacing:.04em;flex:0 0 auto;}
.sw-cat-cmd__copy:hover{background:#C7A961;color:#111;}
.sw-cat-hint{font-size:11px;color:#98a2b3;margin:8px 0 0;}
.sw-cat-price{margin-top:auto;padding:14px 16px;border:1px dashed #d0d5dd;border-radius:8px;background:#fcfcfd;}
.sw-cat-price__amt{font-size:22px;font-weight:700;color:#111;font-family:"Playfair Display",Georgia,serif;}
.sw-cat-price__unit{font-size:13px;color:#667085;margin-left:6px;}
.sw-cat-pay{margin-top:12px;}
.sw-cat-pay__cta{display:inline-flex;align-items:center;justify-content:center;gap:8px;box-sizing:border-box;background:#6c4cf1;color:#fff;font-size:13px;font-weight:600;letter-spacing:.02em;text-decoration:none;padding:10px 16px;border-radius:8px;border:1px solid #5a3fd6;transition:background .12s ease;}
.sw-cat-pay__cta:hover{background:#5a3fd6;}
.sw-cat-pay__cta:focus-visible{outline:2px solid #164679;outline-offset:2px;}
.sw-cat-pay__mark{font-size:14px;line-height:1;}
.sw-cat-pay__meta{margin:8px 0 0;font-size:11.5px;line-height:1.45;color:#667085;}
@media (max-width:768px){.sw-cat-grid{grid-template-columns:1fr;}.sw-cat-wrap{padding:28px 16px 48px;}.sw-cat-pay__cta{display:flex;width:100%;padding:13px 16px;font-size:14px;}}"#;
    html! { style { (PreEscaped(css)) } }
}

/// Vanilla-JS copy-to-clipboard for every `[data-sw-clip]` control. Explicitly in scope
/// for this phase (unlike P2's broader JS-drawer deferral). Small, dependency-free,
/// and degrades silently where the Clipboard API is unavailable.
fn clipboard_script() -> Markup {
    let js = r#"(function(){
document.querySelectorAll('[data-sw-clip]').forEach(function(btn){
  btn.addEventListener('click',function(){
    var text=btn.getAttribute('data-sw-clip');
    if(!navigator.clipboard){return;}
    navigator.clipboard.writeText(text).then(function(){
      var label=btn.getAttribute('data-sw-label')||btn.textContent;
      btn.textContent='Copied';
      setTimeout(function(){btn.textContent=label;},1500);
    }).catch(function(){});
  });
});
})();"#;
    html! { script { (PreEscaped(js)) } }
}

/// Render the full product catalog as body content for the `/software` page.
///
/// Iterates the loaded [`crate::Catalog`] (the same struct `v1_products` serves) — one
/// unified list of os-* products now, grouped by **license tier** (Phase 3 — corrects
/// the free/paid-only grouping this function used before Phase 3 landed). Each
/// product still renders its own BETA-free-vs-paid state individually (see
/// `free_product_card`/`paid_product_card`) — the section boundary is now the
/// ratified tier, matching the pricing page's own PointSav Commercial/FSL split and
/// staying meaningful once real pricing mixes with still-BETA products. The
/// returned [`Markup`] is meant to be wrapped by `layout::render_page`, which
/// supplies the Sovereign Editorial masthead + footer chrome.
pub fn catalog_markup(catalog: &crate::Catalog, source_base_url: &str) -> Markup {
    let (commercial, fsl): (Vec<_>, Vec<_>) = catalog
        .installers
        .iter()
        .partition(|i| i.license_tier == LicenseTier::Commercial);

    let tier_section = |id: &'static str, heading: &'static str, products: &[&crate::Installer]| {
        html! {
            @if !products.is_empty() {
                section."sw-cat-section" id=(id) {
                    h2."sw-cat-section__h" { (heading) }
                    div."sw-cat-grid" {
                        @for i in products {
                            @if i.price_usdc == 0 {
                                (free_product_card(i, source_base_url))
                            } @else {
                                (paid_product_card(i))
                            }
                        }
                    }
                }
            }
        }
    };

    html! {
        (catalog_style())
        div."sw-cat-wrap" {
            h1."sw-cat-intro" { "Products" }
            p."sw-cat-lede" {
                "Buy it once. Run it anywhere. Own it forever. No subscription, no cloud \
                 dependency, no kill switch. Buying your first component here is also your \
                 key to the rest of the stack. This catalog is rendered directly from the \
                 release catalog\u{2014}what you see here is exactly what the download \
                 API serves."
            }
            (tier_section("commercial", "PointSav Commercial", &commercial))
            (tier_section("fsl", "FSL", &fsl))
        }
        (clipboard_script())
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────
//
// Pure rendering functions — no server, no filesystem, no network.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Catalog, Installer};

    const BASE: &str = "https://example.invalid/releases";

    fn fixture() -> Catalog {
        Catalog {
            installers: vec![
                Installer {
                    id: "os-mediakit".into(),
                    name: "MediaKit OS".into(),
                    description: "Sovereign media workstation image.".into(),
                    edition: "1.2.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 812,
                    path: "os-mediakit/1.2.0/installer.run".into(),
                    license_tier: LicenseTier::Fsl,
                    price_usdc: 0, // active BETA gate
                    fsl_conversion_date: None,
                    guide_url: None,
                },
                Installer {
                    id: "os-privategit".into(),
                    name: "PrivateGit OS".into(),
                    description: "Independent code repository.".into(),
                    edition: "1.0.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 150,
                    path: "os-privategit/1.0.0/installer.run".into(),
                    license_tier: LicenseTier::Commercial,
                    price_usdc: 19_000_000, // BETA lifted, test fixture only ($19)
                    fsl_conversion_date: None,
                    guide_url: None,
                },
            ],
        }
    }

    #[test]
    fn install_command_shape_and_trailing_slash_handling() {
        assert_eq!(
            install_command(BASE, "os-mediakit"),
            "curl -fsSL https://example.invalid/releases/os-mediakit/install.sh | bash"
        );
        // A trailing slash on the configured base must not produce a double slash.
        assert_eq!(
            install_command("https://example.invalid/releases/", "x"),
            "curl -fsSL https://example.invalid/releases/x/install.sh | bash"
        );
    }

    #[test]
    fn known_products_appear_in_rendered_markup() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // Known ids and names from the fixture drive the cards (no drift possible).
        assert!(html.contains("os-mediakit"));
        assert!(html.contains("MediaKit OS"));
        assert!(html.contains("os-privategit"));
        assert!(html.contains("PrivateGit OS"));
        assert!(html.contains("FSL"));
        assert!(html.contains("PointSav Commercial"));
        assert!(
            !html.contains("Apache 2.0"),
            "must not use the factually wrong tier label"
        );
        // Each populated tier renders its own section (Phase 3: grouped by license
        // tier, not by free/paid — os-mediakit is FSL, os-privategit is Commercial).
        assert!(html.contains(r#"id="commercial""#));
        assert!(html.contains(r#"id="fsl""#));
        assert!(html.contains("<h2 class=\"sw-cat-section__h\">PointSav Commercial</h2>"));
        assert!(html.contains("<h2 class=\"sw-cat-section__h\">FSL</h2>"));
        // Badge row shows the fields that ARE in the catalog.
        assert!(html.contains("v1.2.0"));
        assert!(html.contains("linux-x86_64"));
        assert!(html.contains("812 MB"));
    }

    #[test]
    fn paid_product_renders_pricing_cta_and_no_install_command() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // Non-zero price_usdc -> price display + Polygon USDC CTA.
        assert!(html.contains("$19.00"));
        assert!(html.contains("Pay with Polygon USDC"));
        assert!(html.contains("href=\"/checkout/os-privategit\""));
        // And NO curl-pipe-sh install command for the paid product.
        assert!(
            !html.contains("releases/os-privategit/install.sh"),
            "paid product must NOT render an install command"
        );
    }

    #[test]
    fn free_products_render_curl_install_commands() {
        let html = catalog_markup(&fixture(), BASE).into_string();
        // price_usdc == 0 -> BETA/free, real curl-pipe-sh command with the right id.
        assert!(html
            .contains("curl -fsSL https://example.invalid/releases/os-mediakit/install.sh | bash"));
        assert!(html.contains("BETA · free"));
        // The copy affordance carries the exact command.
        assert!(html.contains("data-sw-clip"));
    }

    #[test]
    fn empty_catalog_renders_shell_without_sections() {
        let empty = Catalog { installers: vec![] };
        let html = catalog_markup(&empty, BASE).into_string();
        // Page shell still renders…
        assert!(html.contains("sw-cat-intro"));
        // …but no product section.
        assert!(!html.contains("id=\"commercial\""));
        assert!(!html.contains("id=\"fsl\""));
    }

    #[test]
    fn products_are_grouped_by_tier_not_by_prefix_family() {
        // Regression guard for Phase 3: the catalog only ever models os-* installers
        // (tool-wallet, app-*, soft-* never reach this struct at all — they were
        // removed from products.yaml in Phase 1), and cards are grouped by
        // `license_tier`, never by an id-prefix family grid.
        let html = catalog_markup(&fixture(), BASE).into_string();
        assert!(!html.contains("tool-wallet"));
        assert!(!html.contains("Wallet &amp; Tools"));
        assert!(!html.contains("Knowledge &amp; Source"));
        assert!(!html.contains("Orchestration"));
    }
}
